"""Script for preprocessing trees generated by Salping Tree Gen or Tree Gen
a) Converting curve to mesh
b) Separating leaves"""

import bpy

context = bpy.context

scene = context.scene
objects = scene.objects
bpy.ops.object.select_all(action='DESELECT')

# Get "leaves" object and separate by loose parts
for obj in objects:
    if "leaves" in obj.name or "Leaves" in obj.name:
        obj.select_set(True)
        bpy.ops.object.mode_set(mode = 'EDIT')
        bpy.ops.mesh.select_all(action = 'SELECT')
        bpy.ops.mesh.separate(type = 'LOOSE')
        bpy.ops.object.mode_set(mode = 'OBJECT')


# get any curve object (= tree stem/branches) and convert to mesh
for obj in objects:
    if obj.type == 'CURVE':
        bpy.ops.object.select_all(action='DESELECT')
        obj.select_set(True)
        bpy.ops.object.convert(target='MESH')
        bpy.ops.object.select_all(action='DESELECT')
    

